# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160802_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Module'),
        ),
    ]
