# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20160802_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'M\xf3dulo', 'verbose_name_plural': 'M\xf3dulos'},
        ),
        migrations.AlterField(
            model_name='task',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Module', verbose_name=b'm\xc3\xb3dulo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, b'Listo para revisi\xc3\xb3n'), (2, b'Incomplete'), (3, b'Complete')], default=1, editable=False),
        ),
    ]
