# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentwitharchive',
            name='archive',
            field=models.FileField(blank=True, default='', upload_to=b'adjuntos/'),
            preserve_default=False,
        ),
    ]
