# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_task', '0004_cabeceraactividad_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabeceraactividad',
            name='inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cabeceraactividad',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_task.TipoActividad'),
        ),
    ]
