# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_task', '0006_auto_20160824_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabeceraactividad',
            name='asignado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
