# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_task', '0009_cabeceraactividad_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabeceraactividad',
            name='id',
        ),
        migrations.AlterField(
            model_name='cabeceraactividad',
            name='actividad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='new_task.Actividad'),
        ),
    ]
