# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_task', '0010_auto_20160824_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabeceraactividad',
            name='vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
