# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_task', '0016_auto_20160913_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=50)),
                ('funciones', models.TextField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_task.Actividad')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
