# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_task', '0017_usuariosactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosactividad',
            name='usuario_asigando',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariosactividad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
