# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_task', '0020_auto_20160913_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosactividad',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='usuariosactividad',
            name='funciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
