# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_task', '0023_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabeceraactividad',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_task.Area'),
        ),
    ]
