# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_task', '0024_cabeceraactividad_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costo',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_task.CabeceraActividad'),
        ),
    ]
